### ISSUE TITLE
As a Person, I want to register so that I can have an account in the app

### ISSUE THREAD

**Issue by maheshkhanwalkar** [maheshkhanwalkar/BuzzShelter#18]
**Tasks:** 
- [x] Create a Registration Activity and associated controller
- [x] Add textboxes to allow the user to enter in their contact info
- [x] Add a spinner to allow the user to select their User Type
- [x] Create a “Retype Password” input to ensure the user has not mistyped their password in the first box
- [x] Create a Register button which validates the input and proceeds to auto-login the user, so they do not have to manually log in

**Acceptance Scenarios:** 
- GIVEN a user is viewing the Registration page, WHEN the user enters in a valid username, password, retype password, account type, and email, THEN their account is created and they are logged in
- GIVEN a user is viewing the Registration page, WHEN the user does not enter a valid username and/or password and/or retype password and/or account type and/or email, THEN a message is displayed indicating which field(s) were incorrect
- GIVEN a user is viewing the Registration page, WHEN the user does not fill anything or leaves some fields blank, THEN a message is displayed to fill out the blank fields
- GIVEN a user is viewing the Registration page, WHEN the user retypes their password in the second field and it does not match, THEN a message is displayed to indicate the mismatch
- GIVEN a user is viewing the Registration page, WHEN the user hits back or cancel, THEN no account is created and they are taken back to the launch page

**Done Done Criteria:** 
- [x] All the acceptance scenarios have been met
- [x] The changes have been merged into ‘staging’ branch
- [x] Re-run tests to make sure the merged changes in ‘staging’ are still functional when included with the other pieces of the codebase
- [x] _staging_ has been merged into _master_ since this feature is the only thing to implement for M5
- [x] _master_ has been tagged m5-demo to indicate the current spot is ready to be demoed for M5 (stable and working)
